### PR TITLE
Updating CLDR deps and locale handing

### PR DESCRIPTION
**Pull request by kipcole9**
This is looking really good, thanks for getting re-motivated on this.

This PR does 4 things:

1. Update the version requirements for `ex_cldr_*` in `mix.exs` and pull that latest versions.  I left `ex_cldr_messages` pointing to Github.

2. Removed duplicate providers in the `dev` and `test` CLDR backends

3. Changed from using `Cldr.default_locale().cldr_locale_name` to `Cldr.get_locale/0`. `Cldr.get_locale/0` knows about default CLDR backends and so can do a better job of finding the most appropriate CLDR locale in affect. 

4. Adds support for a locale of the type `Cldr.LanguageTag.t` to `Mezzofanti.Backends.GettextBackend.generate_clauses/3`.  It basically redirects to the other clauses using the `cldr_locale_name` element of the struct. Wasn't really sure how to test that in the current test suite but happy to write tests when I get my head around how the backend works.  The reason for proposing this change is that an end-to-end `Cldr` workflow probably sets the locale using `Cldr.Plug.SetLocale` for an incoming http request. If a `Mezzofanti` locale is not set the the locale retrieved will be `Cldr.get_locale/0` which will be of a type `Cldr.LanguageTag.t`. And therefore super helpful if these locale type can be used with the `Mezzofanti.Backends.GettextBackend`

Since as best I can tell, all message formatting ultimately delegates to `Cldr.Message.format/3`, `Cldr.get_locale/0` will pass the fully structured locale (a `Cldr.LanguageTag` struct) which keeps fidelity with the users request. Elements of the structured locale do affect formatting of units, numbers and dates times.

All the current tests pass, warnings on Elixir 1.11 are removed too due to the updated `ex_cldr_*` libs.

### CODE REVIEW

**Comment by tmbb** [comment]
> If a Mezzofanti locale is not set the the locale retrieved will be Cldr.get_locale/0 which will be of a type Cldr.LanguageTag.t. And therefore super helpful if these locale type can be used with the Mezzofanti.Backends.GettextBackend

Could you add Cldr locales named `"peudo"` and "`pseudo_html`" so that one could use it with my pseudolocalization features?

**Comment by tmbb** [comment]
>  I left ex_cldr_messages pointing to Github.

I made it point to tha latest version now that everything is playing well together.

**Comment by kipcole9** [comment]
Just been looking into `pseudo` and `pseudo_html` locales and I think I understand the intent - to check if an UI can responsively handle languages where translations will be longer than the source language.

I can't think of a way yet to have the pseudo locales represented in `Cldr.LanguageTag.t` since that type is very deeply bound to the underlying data of CLDR. 

Let me think on this for a bit and come up with a proposal on how to work this out.

**Comment by tmbb** [comment]
> Just been looking into pseudo and pseudo_html locales and I think I understand the intent - to check if an UI can responsively handle languages where translations will be longer than the source language.

There are two goals for the pseudo locales:
    *  To see if the UI can handle larger strings
    * To see at a glance if the UI contains user-visible messages that are hardcoded and aren't wrapped in a `translate/2` call. That is the reason why we replace "normal" English characters by weird diacritics which are nonetheless recognized as English. If you apply this locale to your app and see a "normal" English string, you've found a message that needs to be wrapped in a `translate/2` call.

> And it actually opens up the possibility later on for language-specific pseudo-localisation which would be very cool.

Yes, I imagine it might be useful if you're writing messages in your code in a language other than English. That would require a way to specify customized pseudo locales, but that seems very easy to do.

**Pull request merged**
